// Timer Types
export interface TimerSession {
  id: string;
  duration: number; // in seconds
  focusTopic: string;
  startedAt: number;
  completedAt?: number;
  status: 'active' | 'paused' | 'completed' | 'abandoned';
}

export interface CalendarEvent {
  id: string;
  title: string;
  startTime: number; // timestamp
  endTime: number;   // timestamp
  color?: string;
  taskId?: string;
  createdFromTimer?: boolean;
}

export type TimerAnimationType = 'coffee' | 'hourglass' | 'battery';

// Note Types
export interface Note {
  id: string;
  title: string;
  content: string;
  createdAt: number;
  updatedAt: number;
  tags: string[];
  isPinned: boolean;
}

// Shop Types
export interface ShopItem {
  id: string;
  name: string;
  description: string;
  category: 'theme' | 'skin' | 'animation';
  price: number; // in coins
  image: string;
  isOwned: boolean;
  isActive: boolean;
}

// Tracker Types - Journal Format
export interface JournalEntry {
  id: string;
  date: number; // timestamp of the entry date (start of day)
  content: string; // Free-form journal content
  createdAt: number; // When the entry was created
  updatedAt: number; // When the entry was last updated
  embedding?: number[]; // Vector embedding for AI analysis (will be generated by backend)
}

// Analytics Types
export interface AnalyticsStat {
  totalFocusTime: number; // in seconds
  totalSessions: number;
  averageSessionLength: number; // in seconds
  longestStreak: number; // in days
  currentStreak: number; // in days
  notesCreated: number;
  journalEntries: number;
}

// AI Analytics Types (from backend)
export interface AIInsight {
  id: string;
  type: 'mood_trend' | 'productivity_pattern' | 'activity_summary' | 'recommendation';
  title: string;
  description: string;
  confidence: number; // 0-100
  period: 'weekly' | 'monthly';
  generatedAt: number;
}

export interface AIAnalytics {
  period: 'weekly' | 'monthly';
  startDate: number;
  endDate: number;
  insights: AIInsight[];
  moodTrend: string; // AI-generated mood summary
  productivityScore: number; // 0-100
  topActivities: string[]; // AI-extracted activities
  recommendations: string[]; // AI suggestions
}

// User/App State Types
export interface UserProfile {
  id: string;
  username: string;
  coins: number;
  totalXP: number;
  level: number;
  theme: 'dark' | 'light';
  timerAnimation: TimerAnimationType;
}

export interface AppState {
  profile: UserProfile;
  currentSession: TimerSession | null;
  timerRunning: boolean;
}

// Task Types
export interface Task {
  id: string;
  taskId: string;
  title: string;
  status: 'Not started' | 'In progress' | 'Done' | 'Re-surface';
  priority?: 'Low' | 'Medium' | 'High';
  dueDate?: string;
  tags?: string[];
  projectId?: string;
  createdAt: number;
}

export interface Project {
  id: string;
  name: string;
  emoji: string;
  collapsed: boolean;
}

// Navigation Types
export type PageType = 'home' | 'timer' | 'notes' | 'shop' | 'tracker' | 'analytics';
